--1. GET TABLE TYPE NOTE
SELECT IDTYPE, TYPENAME, DATE FROM DBO.TYPENOTE

--2. FIND TYPE NAME FROM TABLE
SELECT TYPENAME FROM DBO.TypeNote WHERE TYPENAME = '';

--3. ADD TYPE NAME TO TABLE
INSERT INTO DBO.TYPENOTE (IDTYPE, TYPENAME) VALUES ('', N'')

--4. DELETE TYPE FROM TABLE
DELETE DBO.TYPENOTE WHERE IDTYPE = '';

--5. UPDATE TYPE FROM TABLE
UPDATE DBO.TYPENOTE SET IDTYPE = IDTYPE - 1 WHERE IDTYPE = '3';

